name: Hello GitHub Actions

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [client-dispatched] # the name here is referred to by the dispatch

jobs:

  hello:

    runs-on: ubuntu-latest

    steps:
      - name: Hello, World
        run: echo 'Hello, World'
